language: node_js
cache: yarn
node_js:
  - node
script: yarn run ci
jobs:
  include:
    - stage: semantic-release
      if: branch = master
      node_js: node
      script:
        - npx semantic-release@^15
